// The glossary: Python terms with a short explanation and an example to insert.
// Each entry is tagged three ways, so the panel can group it by topic, by learning path or by question.
// Within a level, entries are listed in the order they're meant to be learned.

/** What kind of thing a term is, like a textbook's table of contents. */
export type Topic = 'basics' | 'collections' | 'helpers' | 'control' | 'functions' | 'errors' | 'patterns' | 'speed'

/** Where a term sits on the learning path, from first steps (1) to going further (4). */
export type Level = 1 | 2 | 3 | 4

/** The question a learner might be asking when they need this term. */
export type Question = 'repeat' | 'decide' | 'remember' | 'find' | 'transform' | 'text' | 'organize' | 'solve' | 'broke'

export interface SyntaxCard {
  id: string
  title: string
  topic: Topic
  level: Level
  questions: Question[]
  keywords: string[]
  explanation: string
  code: string
}

export const TOPICS: { id: Topic; label: string }[] = [
  { id: 'basics', label: 'Basics' },
  { id: 'control', label: 'Control flow' },
  { id: 'collections', label: 'Collections' },
  { id: 'helpers', label: 'Built-in helpers' },
  { id: 'functions', label: 'Functions and classes' },
  { id: 'patterns', label: 'Patterns' },
  { id: 'speed', label: 'Speed (Big-O)' },
  { id: 'errors', label: 'Errors and gotchas' },
]

export const LEVELS: { id: Level; label: string }[] = [
  { id: 1, label: '1. First steps' },
  { id: 2, label: '2. Working with collections' },
  { id: 3, label: '3. Problem-solving patterns' },
  { id: 4, label: '4. Going further' },
]

export const QUESTIONS: { id: Question; label: string }[] = [
  { id: 'remember', label: 'Keep track of things' },
  { id: 'repeat', label: 'Repeat something' },
  { id: 'decide', label: 'Make a decision' },
  { id: 'find', label: 'Find something fast' },
  { id: 'transform', label: 'Change or combine items' },
  { id: 'text', label: 'Work with text' },
  { id: 'organize', label: 'Organize my code' },
  { id: 'solve', label: 'Plan a solution' },
  { id: 'broke', label: 'Something broke' },
]

export const PYTHON_CARDS: SyntaxCard[] = [
  // ---------- Level 1: first steps ----------
  {
    id: 'variables',
    title: 'Variables and assignment',
    topic: 'basics',
    level: 1,
    questions: ['remember'],
    keywords: ['variable', 'assign', 'assignment', 'name', 'equals', 'store'],
    explanation: '= stores a value under a name. Assigning again replaces the old value.',
    code: 'age = 12\nname = "Ada"\nage = age + 1\n',
  },
  {
    id: 'types',
    title: 'Numbers, strings, booleans and None',
    topic: 'basics',
    level: 1,
    questions: ['remember'],
    keywords: ['type', 'types', 'int', 'float', 'str', 'string', 'bool', 'boolean', 'none', 'true', 'false'],
    explanation: 'int is a whole number, float has a decimal point, str is text, bool is True or False, and None means "nothing yet".',
    code: 'count = 3\nprice = 2.5\nword = "hi"\ndone = False\nanswer = None\nkind = type(price)\n',
  },
  {
    id: 'math',
    title: 'Math operators',
    topic: 'basics',
    level: 1,
    questions: ['transform'],
    keywords: ['math', 'add', 'subtract', 'multiply', 'divide', 'modulo', 'remainder', 'power', 'floor', 'operator'],
    explanation: '/ always gives a float, // drops the remainder, % gives the remainder, ** is a power.',
    code: 'a = 7 / 2    # 3.5\nb = 7 // 2   # 3\nc = 7 % 2    # 1, so 7 is odd\nd = 2 ** 5   # 32\n',
  },
  {
    id: 'augmented',
    title: 'Updating a variable (+=)',
    topic: 'basics',
    level: 1,
    questions: ['remember', 'repeat'],
    keywords: ['plus', 'equals', 'increment', 'add', 'update', 'counter', 'augmented'],
    explanation: 'total += n is short for total = total + n. There is also -=, *= and //=.',
    code: 'total = 0\nfor n in [4, 8, 15]:\n    total += n\n',
  },
  {
    id: 'print',
    title: 'print and f-strings',
    topic: 'basics',
    level: 1,
    questions: ['text'],
    keywords: ['print', 'output', 'fstring', 'f', 'format', 'show', 'display'],
    explanation: 'print writes to the console. Put f before a string to drop values into it with {braces}.',
    code: 'name = "Ada"\nscore = 42\nprint("hello")\nprint(f"{name} scored {score}")\n',
  },
  {
    id: 'comments',
    title: 'Comments',
    topic: 'basics',
    level: 1,
    questions: ['organize'],
    keywords: ['comment', 'hash', 'note', 'explain'],
    explanation: 'Everything after # on a line is ignored by Python. Use comments to say why, not what.',
    code: '# the partner we need to reach the target\nneed = 9 - 2\n',
  },
  {
    id: 'comparisons',
    title: 'Comparisons',
    topic: 'basics',
    level: 1,
    questions: ['decide'],
    keywords: ['compare', 'comparison', 'equal', 'equals', 'greater', 'less', 'not', 'condition'],
    explanation: '== checks equality (= assigns). Also != , <, <=, > and >=. Each gives True or False.',
    code: 'x = 7\nis_seven = x == 7\nbig = x > 10\nin_range = 0 <= x < 10\n',
  },
  {
    id: 'boolean-logic',
    title: 'and, or, not',
    topic: 'basics',
    level: 1,
    questions: ['decide'],
    keywords: ['and', 'or', 'not', 'boolean', 'logic', 'condition', 'combine'],
    explanation: 'and needs both sides True, or needs either, not flips it.',
    code: 'age = 15\nteen = age >= 13 and age <= 19\nweekend = False\nfree = weekend or age < 5\nbusy = not weekend\n',
  },
  {
    id: 'if-elif-else',
    title: 'If / elif / else',
    topic: 'control',
    level: 1,
    questions: ['decide'],
    keywords: ['if', 'else', 'elif', 'condition', 'branch'],
    explanation: 'Checks conditions top to bottom and runs the first block that matches.',
    code: 'x = 7\nif x > 10:\n    size = "big"\nelif x > 5:\n    size = "medium"\nelse:\n    size = "small"\n',
  },
  {
    id: 'for-list',
    title: 'For loop over a list',
    topic: 'control',
    level: 1,
    questions: ['repeat'],
    keywords: ['for', 'loop', 'iterate', 'each', 'array', 'list'],
    explanation: 'Visits each item in order. The loop variable holds the item itself, not its index.',
    code: 'nums = [4, 8, 15]\nfor n in nums:\n    print(n)\n',
  },
  {
    id: 'range',
    title: 'range',
    topic: 'helpers',
    level: 1,
    questions: ['repeat'],
    keywords: ['range', 'count', 'numbers', 'step', 'times', 'loop'],
    explanation: 'range(stop) counts from 0 up to, but not including, stop. range(start, stop, step) can skip or count down.',
    code: 'for i in range(3):\n    print(i)          # 0 1 2\n\nfor i in range(10, 0, -3):\n    print(i)          # 10 7 4 1\n',
  },
  {
    id: 'for-index',
    title: 'For loop with an index',
    topic: 'control',
    level: 1,
    questions: ['repeat'],
    keywords: ['for', 'loop', 'index', 'range', 'len', 'enumerate', 'i'],
    explanation: 'Use range(len(...)) when you need the position, or enumerate to get both.',
    code: 'nums = [4, 8, 15]\nfor i in range(len(nums)):\n    print(i, nums[i])\n\nfor i, n in enumerate(nums):\n    print(i, n)\n',
  },
  {
    id: 'while',
    title: 'While loop',
    topic: 'control',
    level: 1,
    questions: ['repeat'],
    keywords: ['while', 'loop', 'until', 'condition'],
    explanation: 'Repeats as long as the condition is true. Remember to change something so it ends.',
    code: 'count = 3\nwhile count > 0:\n    print(count)\n    count -= 1\n',
  },
  {
    id: 'break-continue',
    title: 'break and continue',
    topic: 'control',
    level: 1,
    questions: ['repeat'],
    keywords: ['break', 'continue', 'stop', 'skip', 'exit', 'loop'],
    explanation: 'break leaves the loop right away. continue skips the rest of this pass and goes to the next item.',
    code: 'for n in [3, -1, 4, 0, 5]:\n    if n < 0:\n        continue      # skip negatives\n    if n == 0:\n        break         # stop at the first zero\n    print(n)\n',
  },
  {
    id: 'functions',
    title: 'Functions',
    topic: 'functions',
    level: 1,
    questions: ['organize'],
    keywords: ['function', 'def', 'return', 'method', 'arguments'],
    explanation: 'def names a block of code that takes inputs and can return a result.',
    code: 'def total(xs):\n    s = 0\n    for x in xs:\n        s += x\n    return s\n\nresult = total([1, 2, 3])\n',
  },
  {
    id: 'return-vs-print',
    title: 'return vs print',
    topic: 'functions',
    level: 1,
    questions: ['organize', 'broke'],
    keywords: ['return', 'print', 'difference', 'result', 'output', 'none'],
    explanation: 'print only shows a value. return hands it back to the caller, which is what the tests check.',
    code: 'def shows(x):\n    print(x * 2)\n\ndef gives(x):\n    return x * 2\n\na = shows(5)   # prints 10, but a is None\nb = gives(5)   # b is 10\n',
  },

  // ---------- Level 2: working with collections ----------
  {
    id: 'lists',
    title: 'Lists',
    topic: 'collections',
    level: 2,
    questions: ['remember'],
    keywords: ['list', 'array', 'append', 'pop', 'slice', 'length'],
    explanation: 'Lists are ordered and mutable. Index from 0; negative indexes count from the end.',
    code: 'a = [3, 1, 2]\na.append(5)\nlast = a.pop()\nfirst = a[0]\nend = a[-1]\nmiddle = a[1:3]\nsize = len(a)\n',
  },
  {
    id: 'slicing',
    title: 'Indexing and slicing',
    topic: 'collections',
    level: 2,
    questions: ['find', 'text'],
    keywords: ['index', 'slice', 'slicing', 'colon', 'reverse', 'sublist', 'substring', 'negative'],
    explanation: 'a[start:stop] takes items from start up to, not including, stop. Leave a side out to go to the end; a[::-1] is reversed.',
    code: 'a = [10, 20, 30, 40, 50]\nfirst_two = a[:2]     # [10, 20]\nlast_two = a[-2:]     # [40, 50]\nevery_other = a[::2]  # [10, 30, 50]\nbackwards = a[::-1]\n',
  },
  {
    id: 'strings',
    title: 'Strings',
    topic: 'collections',
    level: 2,
    questions: ['text'],
    keywords: ['string', 'str', 'text', 'char', 'character', 'letter', 'word'],
    explanation: 'A string is a sequence of characters. You can index, slice and loop over it like a list, but you cannot change it in place.',
    code: 'word = "hello"\nfirst = word[0]\nfor ch in word:\n    print(ch)\nshout = word.upper()\n',
  },
  {
    id: 'string-methods',
    title: 'split, join, strip, lower',
    topic: 'collections',
    level: 2,
    questions: ['text', 'transform'],
    keywords: ['split', 'join', 'strip', 'lower', 'upper', 'replace', 'string', 'words'],
    explanation: 'split breaks a string into a list, join glues a list back together, strip trims spaces, lower and upper change case.',
    code: 'line = "  The quick fox  "\nwords = line.strip().lower().split()\nback = "-".join(words)    # "the-quick-fox"\n',
  },
  {
    id: 'tuples',
    title: 'Tuples and unpacking',
    topic: 'collections',
    level: 2,
    questions: ['remember'],
    keywords: ['tuple', 'unpack', 'unpacking', 'swap', 'pair', 'multiple'],
    explanation: 'A tuple is a fixed group of values. Unpacking assigns each one to its own name, which makes swapping a one-liner.',
    code: 'point = (3, 4)\nx, y = point\na, b = 1, 2\na, b = b, a      # swap\n',
  },
  {
    id: 'dicts',
    title: 'Dictionaries (hash maps)',
    topic: 'collections',
    level: 2,
    questions: ['remember', 'find'],
    keywords: ['dict', 'dictionary', 'map', 'hash', 'hashmap', 'key', 'value', 'count'],
    explanation: 'Key to value lookups in constant time. The workhorse of many LeetCode problems.',
    code: 'counts = {}\nfor ch in "banana":\n    counts[ch] = counts.get(ch, 0) + 1\n',
  },
  {
    id: 'dict-loops',
    title: 'Looping over a dict',
    topic: 'collections',
    level: 2,
    questions: ['repeat'],
    keywords: ['dict', 'items', 'keys', 'values', 'loop', 'iterate'],
    explanation: 'Looping over a dict gives its keys. .items() gives key and value together, .values() just the values.',
    code: 'ages = {"ana": 12, "ben": 9}\nfor name in ages:\n    print(name)\nfor name, age in ages.items():\n    print(name, age)\ntotal = sum(ages.values())\n',
  },
  {
    id: 'sets',
    title: 'Sets',
    topic: 'collections',
    level: 2,
    questions: ['remember', 'find'],
    keywords: ['set', 'unique', 'duplicate', 'duplicates', 'seen', 'add', 'distinct'],
    explanation: 'A set holds unique values with fast "is it in there?" checks. Great for spotting duplicates.',
    code: 'seen = set()\nfor n in [3, 1, 3, 2]:\n    if n in seen:\n        print("duplicate", n)\n    seen.add(n)\nunique = set([1, 1, 2])   # {1, 2}\n',
  },
  {
    id: 'membership',
    title: 'in (membership)',
    topic: 'collections',
    level: 2,
    questions: ['find', 'decide'],
    keywords: ['in', 'contains', 'membership', 'exists', 'has', 'check'],
    explanation: 'x in thing is True when x is there. Fast for sets and dict keys, slow for long lists.',
    code: 'vowels = "aeiou"\nis_vowel = "e" in vowels\nages = {"ana": 12}\nknown = "ana" in ages\nmissing = 5 not in [1, 2, 3]\n',
  },
  {
    id: 'truthiness',
    title: 'Truthiness',
    topic: 'basics',
    level: 2,
    questions: ['decide', 'broke'],
    keywords: ['truthy', 'falsy', 'empty', 'zero', 'none', 'if', 'bool'],
    explanation: '0, empty strings, empty lists, empty dicts and None all count as False in an if. Everything else counts as True.',
    code: 'stack = []\nif not stack:\n    print("empty")\nname = ""\nlabel = name or "anonymous"\n',
  },
  {
    id: 'nested-loops',
    title: 'Nested loops',
    topic: 'control',
    level: 2,
    questions: ['repeat'],
    keywords: ['nested', 'loop', 'inner', 'outer', 'pairs', 'grid', 'matrix'],
    explanation: 'A loop inside a loop runs the inner one fully for every pass of the outer one. Handy for pairs and grids, but slow on big inputs.',
    code: 'nums = [1, 2, 3]\nfor i in range(len(nums)):\n    for j in range(i + 1, len(nums)):\n        print(nums[i], nums[j])\n',
  },
  {
    id: 'early-return',
    title: 'Early return',
    topic: 'control',
    level: 2,
    questions: ['decide', 'organize'],
    keywords: ['return', 'early', 'exit', 'stop', 'found', 'guard'],
    explanation: 'return ends the function on the spot, even inside a loop. Return as soon as you have the answer.',
    code: 'def first_even(nums):\n    for n in nums:\n        if n % 2 == 0:\n            return n\n    return None\n\nfound = first_even([3, 7, 8, 10])\n',
  },
  {
    id: 'zip',
    title: 'zip',
    topic: 'helpers',
    level: 2,
    questions: ['repeat', 'transform'],
    keywords: ['zip', 'pair', 'together', 'parallel', 'combine', 'two', 'lists'],
    explanation: 'zip walks two (or more) lists side by side, giving one item from each per step.',
    code: 'names = ["ana", "ben"]\nscores = [90, 85]\nfor name, score in zip(names, scores):\n    print(name, score)\nby_name = dict(zip(names, scores))\n',
  },
  {
    id: 'min-max-sum',
    title: 'min, max, sum, len',
    topic: 'helpers',
    level: 2,
    questions: ['find', 'transform'],
    keywords: ['min', 'max', 'sum', 'len', 'smallest', 'largest', 'biggest', 'total', 'count'],
    explanation: 'Built-ins that go through a whole list for you. Each one is a hidden loop.',
    code: 'nums = [4, 8, 15, 16]\nsmallest = min(nums)\nlargest = max(nums)\ntotal = sum(nums)\naverage = total / len(nums)\n',
  },
  {
    id: 'sorting',
    title: 'sorted vs .sort()',
    topic: 'helpers',
    level: 2,
    questions: ['transform'],
    keywords: ['sort', 'sorted', 'order', 'key', 'reverse', 'descending'],
    explanation: 'sorted(a) returns a new sorted list; a.sort() sorts in place and returns None. key= chooses what to sort by.',
    code: 'nums = [3, 1, 2]\nnew = sorted(nums)\nnums.sort(reverse=True)\nwords = ["kiwi", "fig", "banana"]\nby_length = sorted(words, key=len)\n',
  },
  {
    id: 'list-comprehension',
    title: 'List comprehensions',
    topic: 'collections',
    level: 2,
    questions: ['transform'],
    keywords: ['comprehension', 'list', 'map', 'filter', 'transform', 'square', 'one', 'line'],
    explanation: 'Builds a new list from another in one line: [expression for item in list if condition].',
    code: 'nums = [1, 2, 3, 4]\nsquares = [n * n for n in nums]\nevens = [n for n in nums if n % 2 == 0]\n',
  },
  {
    id: 'dict-comprehension',
    title: 'Dict comprehensions',
    topic: 'collections',
    level: 2,
    questions: ['transform'],
    keywords: ['comprehension', 'dict', 'dictionary', 'build', 'map', 'index'],
    explanation: 'Like a list comprehension, but with key: value. Handy for "where is each value?" lookups.',
    code: 'nums = [10, 20, 30]\nindex_of = {n: i for i, n in enumerate(nums)}\nlengths = {w: len(w) for w in ["hi", "hello"]}\n',
  },
  {
    id: 'index-error',
    title: 'IndexError',
    topic: 'errors',
    level: 2,
    questions: ['broke'],
    keywords: ['indexerror', 'index', 'out', 'range', 'error', 'list'],
    explanation: '"list index out of range" means you asked for a position the list does not have. The last index is len(a) - 1.',
    code: 'a = [10, 20, 30]\n# a[3] would crash: indexes are 0, 1, 2\nlast = a[len(a) - 1]\nif 3 < len(a):\n    print(a[3])\n',
  },
  {
    id: 'key-error',
    title: 'KeyError',
    topic: 'errors',
    level: 2,
    questions: ['broke'],
    keywords: ['keyerror', 'key', 'missing', 'error', 'dict', 'get'],
    explanation: 'The key is not in the dict. Check with in first, or use .get(key, default).',
    code: 'ages = {"ana": 12}\n# ages["ben"] would crash\nben = ages.get("ben", 0)\nif "ben" in ages:\n    print(ages["ben"])\n',
  },
  {
    id: 'type-error',
    title: 'TypeError',
    topic: 'errors',
    level: 2,
    questions: ['broke'],
    keywords: ['typeerror', 'type', 'error', 'concatenate', 'str', 'int', 'unsupported'],
    explanation: 'An operation got the wrong kind of value, like adding a number to a string. Convert one side with str() or int().',
    code: 'age = 12\n# "age " + age would crash\nlabel = "age " + str(age)\nn = int("42") + 1\n',
  },
  {
    id: 'off-by-one',
    title: 'Off-by-one',
    topic: 'errors',
    level: 2,
    questions: ['broke'],
    keywords: ['off', 'one', 'boundary', 'range', 'last', 'missing', 'extra'],
    explanation: 'Starting or stopping one step too early or late. Check the first and last pass of the loop by hand.',
    code: 'nums = [1, 2, 3]\n# range(len(nums) - 1) would skip the 3\nfor i in range(len(nums)):\n    print(nums[i])\n',
  },
  {
    id: 'infinite-loop',
    title: 'Infinite loop',
    topic: 'errors',
    level: 2,
    questions: ['broke'],
    keywords: ['infinite', 'forever', 'stuck', 'hang', 'while', 'loop', 'never', 'ends'],
    explanation: 'A while loop whose condition never becomes False. Make sure every pass moves toward the end.',
    code: 'count = 3\nwhile count > 0:\n    print(count)\n    count -= 1    # without this line it never ends\n',
  },
  {
    id: 'missing-return',
    title: 'Got None back',
    topic: 'errors',
    level: 2,
    questions: ['broke'],
    keywords: ['none', 'return', 'missing', 'forgot', 'nothing', 'result'],
    explanation: 'A function with no return (or one that only prints) gives back None. Also watch for paths that skip the return.',
    code: 'def double(x):\n    result = x * 2\n    return result     # without this, double(4) is None\n\nanswer = double(4)\n',
  },

  // ---------- Level 3: problem-solving patterns ----------
  {
    id: 'big-o',
    title: 'Big-O in plain words',
    topic: 'speed',
    level: 3,
    questions: ['solve'],
    keywords: ['big', 'o', 'complexity', 'speed', 'fast', 'slow', 'time', 'efficient'],
    explanation: 'How the work grows as the input grows. O(n) is one pass over the list; O(n²) is a loop inside a loop; O(1) does not grow at all.',
    code: 'nums = [5, 3, 8]\n# O(n): look at each item once\ntotal = sum(nums)\n# O(n²): every pair\npairs = [(a, b) for a in nums for b in nums]\n',
  },
  {
    id: 'dict-vs-list-lookup',
    title: 'Why dict lookups are fast',
    topic: 'speed',
    level: 3,
    questions: ['find', 'solve'],
    keywords: ['lookup', 'fast', 'dict', 'set', 'list', 'search', 'hash', 'o1'],
    explanation: '"x in a_list" checks items one by one, O(n). "x in a_set" or a dict key jumps straight there, O(1).',
    code: 'nums = list(range(1000))\nslow = 999 in nums        # checks up to 1000 items\nfast_set = set(nums)\nfast = 999 in fast_set    # one jump\n',
  },
  {
    id: 'hash-map-lookup',
    title: 'Hash map lookup',
    topic: 'patterns',
    level: 3,
    questions: ['find', 'solve'],
    keywords: ['hash', 'map', 'lookup', 'seen', 'complement', 'pair', 'twosum', 'dict', 'pattern'],
    explanation: 'Remember what you have seen in a dict, then ask "have I already seen the partner I need?" in one step.',
    code: 'nums, target = [2, 7, 11, 15], 9\nseen = {}\nfor i, n in enumerate(nums):\n    need = target - n\n    if need in seen:\n        print(seen[need], i)\n    seen[n] = i\n',
  },
  {
    id: 'counting',
    title: 'Counting things',
    topic: 'patterns',
    level: 3,
    questions: ['remember', 'solve'],
    keywords: ['count', 'counting', 'frequency', 'tally', 'anagram', 'occurrences', 'pattern'],
    explanation: 'Keep a dict of value to count. Two things are anagrams when their counts match.',
    code: 'def counts(word):\n    c = {}\n    for ch in word:\n        c[ch] = c.get(ch, 0) + 1\n    return c\n\nsame = counts("listen") == counts("silent")\n',
  },
  {
    id: 'running-best',
    title: 'Running best (accumulator)',
    topic: 'patterns',
    level: 3,
    questions: ['remember', 'solve'],
    keywords: ['running', 'best', 'max', 'min', 'so', 'far', 'accumulator', 'track', 'pattern'],
    explanation: 'Keep one variable for the best answer so far and update it only when something beats it.',
    code: 'prices = [7, 1, 5, 3, 6, 4]\nlowest = prices[0]\nprofit = 0\nfor p in prices:\n    lowest = min(lowest, p)\n    profit = max(profit, p - lowest)\n',
  },
  {
    id: 'two-pointers',
    title: 'Two pointers',
    topic: 'patterns',
    level: 3,
    questions: ['solve'],
    keywords: ['two', 'pointers', 'left', 'right', 'reverse', 'leetcode', 'l', 'r', 'pattern'],
    explanation: 'Start one index at each end and walk them toward each other.',
    code: 'a = [1, 2, 3, 4, 5]\nl, r = 0, len(a) - 1\nwhile l < r:\n    a[l], a[r] = a[r], a[l]\n    l += 1\n    r -= 1\n',
  },
  {
    id: 'slow-fast',
    title: 'Slow and fast pointers',
    topic: 'patterns',
    level: 3,
    questions: ['solve'],
    keywords: ['slow', 'fast', 'pointers', 'write', 'read', 'in', 'place', 'zeroes', 'pattern'],
    explanation: 'Both pointers start at the front. fast reads every item; slow marks where the next kept item goes.',
    code: 'a = [0, 1, 0, 3, 12]\nslow = 0\nfor fast in range(len(a)):\n    if a[fast] != 0:\n        a[slow], a[fast] = a[fast], a[slow]\n        slow += 1\n',
  },
  {
    id: 'sliding-window',
    title: 'Sliding window',
    topic: 'patterns',
    level: 3,
    questions: ['solve'],
    keywords: ['sliding', 'window', 'substring', 'subarray', 'left', 'right', 'longest', 'pattern'],
    explanation: 'Grow a window with right, and shrink it from left when it breaks a rule. Each item enters and leaves once.',
    code: 's = "abcabcbb"\nlast = {}\nleft = 0\nbest = 0\nfor right, ch in enumerate(s):\n    if ch in last and last[ch] >= left:\n        left = last[ch] + 1\n    last[ch] = right\n    best = max(best, right - left + 1)\n',
  },
  {
    id: 'stack',
    title: 'Stack',
    topic: 'patterns',
    level: 3,
    questions: ['remember', 'solve'],
    keywords: ['stack', 'push', 'pop', 'last', 'parentheses', 'brackets', 'lifo', 'pattern'],
    explanation: 'A list where you only append and pop at the end: last in, first out. Perfect for matching brackets.',
    code: 'pairs = {")": "(", "]": "["}\nstack = []\nok = True\nfor ch in "([])":\n    if ch in pairs:\n        ok = ok and bool(stack) and stack.pop() == pairs[ch]\n    else:\n        stack.append(ch)\nok = ok and not stack\n',
  },
  {
    id: 'binary-search',
    title: 'Binary search',
    topic: 'patterns',
    level: 3,
    questions: ['find', 'solve'],
    keywords: ['binary', 'search', 'sorted', 'half', 'mid', 'lo', 'hi', 'log', 'pattern'],
    explanation: 'On a sorted list, look at the middle and throw away the half that cannot hold the answer. O(log n).',
    code: 'a = [1, 3, 5, 7, 9, 11]\ntarget = 7\nlo, hi = 0, len(a) - 1\nwhile lo <= hi:\n    mid = (lo + hi) // 2\n    if a[mid] == target:\n        break\n    elif a[mid] < target:\n        lo = mid + 1\n    else:\n        hi = mid - 1\n',
  },
  {
    id: 'prefix-sum',
    title: 'Prefix sums',
    topic: 'patterns',
    level: 3,
    questions: ['solve'],
    keywords: ['prefix', 'sum', 'running', 'total', 'range', 'cumulative', 'pattern'],
    explanation: 'Store the running total at each position. Then the sum of any slice is one subtraction.',
    code: 'nums = [3, 1, 4, 1, 5]\nprefix = [0]\nfor n in nums:\n    prefix.append(prefix[-1] + n)\n# sum of nums[1:4]\npart = prefix[4] - prefix[1]\n',
  },
  {
    id: 'sort-first',
    title: 'Sort first',
    topic: 'patterns',
    level: 3,
    questions: ['solve'],
    keywords: ['sort', 'first', 'sorted', 'order', 'neighbors', 'group', 'pattern'],
    explanation: 'Sorting puts equal or close values next to each other, which often turns a hard problem into one pass.',
    code: 'nums = [4, 1, 3, 1, 2]\nnums.sort()\nhas_dup = any(nums[i] == nums[i + 1] for i in range(len(nums) - 1))\n',
  },
  {
    id: 'aliasing',
    title: 'Two names, one list',
    topic: 'errors',
    level: 3,
    questions: ['broke'],
    keywords: ['alias', 'aliasing', 'copy', 'reference', 'same', 'list', 'changed'],
    explanation: 'b = a does not copy a list; both names point at the same one. Use a.copy() or a[:] for a real copy.',
    code: 'a = [1, 2]\nb = a\nb.append(3)     # a is [1, 2, 3] too\nc = a.copy()\nc.append(4)     # a is unchanged\n',
  },
  {
    id: 'mutate-while-looping',
    title: 'Changing a list while looping over it',
    topic: 'errors',
    level: 3,
    questions: ['broke'],
    keywords: ['remove', 'delete', 'loop', 'skip', 'modify', 'mutate', 'while', 'iterating'],
    explanation: 'Removing items from the list you are looping over makes the loop skip items. Build a new list instead.',
    code: 'nums = [1, 2, 2, 3]\n# for n in nums: nums.remove(n) skips items\nkept = [n for n in nums if n != 2]\n',
  },

  // ---------- Level 4: going further ----------
  {
    id: 'recursion',
    title: 'Recursion',
    topic: 'functions',
    level: 4,
    questions: ['repeat', 'solve'],
    keywords: ['recursion', 'recursive', 'base', 'case', 'calls', 'itself', 'factorial'],
    explanation: 'A function that calls itself on a smaller input. It needs a base case that stops the calls.',
    code: 'def factorial(n):\n    if n <= 1:         # base case\n        return 1\n    return n * factorial(n - 1)\n\nanswer = factorial(4)\n',
  },
  {
    id: 'memoization',
    title: 'Memoization and DP',
    topic: 'patterns',
    level: 4,
    questions: ['remember', 'solve'],
    keywords: ['memo', 'memoization', 'dp', 'dynamic', 'programming', 'cache', 'fibonacci', 'stairs'],
    explanation: 'Save answers to smaller problems so you never solve the same one twice, either in a dict or by filling a list.',
    code: 'n = 6\nways = [1, 1]\nfor i in range(2, n + 1):\n    ways.append(ways[i - 1] + ways[i - 2])\nanswer = ways[n]\n',
  },
  {
    id: 'default-params',
    title: 'Default and keyword arguments',
    topic: 'functions',
    level: 4,
    questions: ['organize'],
    keywords: ['default', 'parameter', 'argument', 'keyword', 'optional', 'named'],
    explanation: 'A parameter can have a default value, and callers can pass arguments by name.',
    code: 'def greet(name, greeting="hi"):\n    return f"{greeting} {name}"\n\na = greet("ana")\nb = greet("ben", greeting="hey")\n',
  },
  {
    id: 'scope',
    title: 'Scope',
    topic: 'functions',
    level: 4,
    questions: ['organize', 'broke'],
    keywords: ['scope', 'local', 'global', 'inside', 'outside', 'variable', 'function'],
    explanation: 'Variables made inside a function exist only inside it. Pass values in as arguments and return them out.',
    code: 'def make():\n    inside = 5\n    return inside\n\nvalue = make()\n# print(inside) here would be a NameError\n',
  },
  {
    id: 'lambda',
    title: 'lambda',
    topic: 'functions',
    level: 4,
    questions: ['transform'],
    keywords: ['lambda', 'anonymous', 'key', 'sort', 'function', 'inline'],
    explanation: 'A tiny one-expression function with no name. Mostly used as key= when sorting.',
    code: 'people = [("ana", 12), ("ben", 9)]\nby_age = sorted(people, key=lambda p: p[1])\n',
  },
  {
    id: 'counter',
    title: 'collections.Counter',
    topic: 'helpers',
    level: 4,
    questions: ['remember'],
    keywords: ['counter', 'count', 'collections', 'frequency', 'most', 'common'],
    explanation: 'A dict made for counting. Counter("banana") counts every letter for you.',
    code: 'from collections import Counter\nc = Counter("banana")\ntop = c.most_common(1)   # [("a", 3)]\n',
  },
  {
    id: 'defaultdict',
    title: 'collections.defaultdict',
    topic: 'helpers',
    level: 4,
    questions: ['remember'],
    keywords: ['defaultdict', 'default', 'dict', 'group', 'collections', 'missing'],
    explanation: 'A dict that creates a starting value for missing keys, so grouping needs no "if key not in" check.',
    code: 'from collections import defaultdict\ngroups = defaultdict(list)\nfor w in ["eat", "tea", "tan"]:\n    groups["".join(sorted(w))].append(w)\n',
  },
  {
    id: 'deque',
    title: 'collections.deque',
    topic: 'helpers',
    level: 4,
    questions: ['remember', 'solve'],
    keywords: ['deque', 'queue', 'popleft', 'bfs', 'collections', 'front'],
    explanation: 'A list that is fast at both ends. Use it as a queue: append at the back, popleft from the front.',
    code: 'from collections import deque\nq = deque([1, 2])\nq.append(3)\nfirst = q.popleft()   # 1\n',
  },
  {
    id: 'heapq',
    title: 'heapq',
    topic: 'helpers',
    level: 4,
    questions: ['find'],
    keywords: ['heap', 'heapq', 'priority', 'queue', 'smallest', 'kth', 'top'],
    explanation: 'Keeps the smallest item ready to pop in O(log n). Good for "k smallest" or "always take the cheapest next".',
    code: 'import heapq\nh = [5, 1, 8, 3]\nheapq.heapify(h)\nsmallest = heapq.heappop(h)\ntwo_largest = heapq.nlargest(2, [5, 1, 8, 3])\n',
  },
  {
    id: 'classes',
    title: 'Classes',
    topic: 'functions',
    level: 4,
    questions: ['organize', 'remember'],
    keywords: ['class', 'object', 'init', 'self', 'node', 'linked', 'tree', 'attribute'],
    explanation: 'A class is a blueprint for your own kind of value. __init__ sets it up and self is the object itself.',
    code: 'class Node:\n    def __init__(self, val, next=None):\n        self.val = val\n        self.next = next\n\nhead = Node(1, Node(2))\nsecond = head.next.val\n',
  },
]

export type GroupBy = 'topic' | 'level' | 'question'

export interface CardGroup {
  id: string
  label: string
  cards: SyntaxCard[]
}

/**
 * Sort cards into groups: by topic, by learning path (in path order), or by question.
 * A card can sit under several questions. Empty groups are left out.
 */
export function groupCards(cards: SyntaxCard[], by: GroupBy): CardGroup[] {
  const groups =
    by === 'topic'
      ? TOPICS.map((t) => ({ id: t.id, label: t.label, cards: cards.filter((c) => c.topic === t.id) }))
      : by === 'level'
        ? LEVELS.map((l) => ({ id: String(l.id), label: l.label, cards: cards.filter((c) => c.level === l.id) }))
        : QUESTIONS.map((q) => ({ id: q.id, label: q.label, cards: cards.filter((c) => c.questions.includes(q.id)) }))
  return groups.filter((g) => g.cards.length > 0)
}

/** Rank cards by how many query words match their title or keywords. */
export function searchCards(query: string, cards = PYTHON_CARDS): SyntaxCard[] {
  const words = query.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)
  if (words.length === 0) return cards
  return cards
    .map((card) => {
      const hay = [...card.keywords, ...card.title.toLowerCase().split(/[^a-z0-9]+/)]
      return { card, score: words.filter((w) => hay.includes(w)).length }
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((x) => x.card)
}
